---
- name: create group
  tasks:
  - name: using group module
    group:
      name: jsm
      state: present
      gid: 2000

  - name: using user module
    ansible.builtin.user:
      name: mini
      uid: 2000
      group: jsm
